import os
import tempfile
import unittest

from slopguard.diranalyzer import (
    AnalysisOptions,
    analyze_tree,
    default_analysis_options,
)
from slopguard.errors import ERR_FILE_NOT_FOUND, SlopguardError


def write(path, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)


class DirAnalyzerTests(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp(prefix="slopdir-")
        write(os.path.join(self.dir, "app.py"), "def a():\n    return 1\n")
        write(os.path.join(self.dir, "tests", "test_app.py"), "def test_a():\n    assert True\n")
        write(os.path.join(self.dir, ".venv", "lib.py"), "def hidden():\n    return 1\n")
        write(os.path.join(self.dir, "gen", "foo_pb2.py"), "def gen():\n    return 1\n")

    def paths(self, options):
        return sorted(r.path for r in analyze_tree(self.dir, options))

    def test_default_excludes(self):
        # tests/, .venv (hidden), and *_pb2.py are excluded by default.
        self.assertEqual(self.paths(default_analysis_options()), ["app.py"])

    def test_no_default_excludes_includes_tests(self):
        # Hidden dirs (.venv) are always skipped, but test files come back.
        got = self.paths(AnalysisOptions())
        self.assertIn("app.py", got)
        self.assertIn("tests/test_app.py", got)
        self.assertIn("gen/foo_pb2.py", got)

    def test_include_filter(self):
        opts = default_analysis_options()
        opts.include_globs = ["**/app.py"]
        self.assertEqual(self.paths(opts), ["app.py"])

    def test_single_file(self):
        reports = analyze_tree(os.path.join(self.dir, "app.py"), AnalysisOptions())
        self.assertEqual(len(reports), 1)
        self.assertEqual(reports[0].path, "app.py")

    def test_missing_path_raises(self):
        with self.assertRaises(SlopguardError) as ctx:
            analyze_tree(os.path.join(self.dir, "nope"), default_analysis_options())
        self.assertEqual(ctx.exception.code, ERR_FILE_NOT_FOUND)

    def test_generated_header_skipped(self):
        write(
            os.path.join(self.dir, "machine.py"),
            "# @generated by a tool\ndef huge(a, b):\n    return a and b\n",
        )
        reports = {r.path: r for r in analyze_tree(self.dir, default_analysis_options())}
        self.assertIn("machine.py", reports)
        self.assertEqual(len(reports["machine.py"].methods), 0)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
