"""Single-file analysis: read a Python source file and analyze it.

Generated files (per the conventional ``@generated`` / "DO NOT EDIT" markers
some Python codegen stamps) yield an empty report so their branchy output
doesn't pollute the numbers — mirroring the Go port skipping ``DO NOT EDIT``
files and the TypeScript port skipping ``*.generated.*``.
"""

from __future__ import annotations

import re

from .complexity import analyze_source
from .errors import unreadable_file
from .models import FileReport

_GENERATED_HEADER = re.compile(
    r"(?m)^#.*(?:@generated\b|DO NOT EDIT|Generated by the protocol buffer compiler)"
)


def is_python_source(path: str) -> bool:
    """True for an analyzable Python source file. ``.pyi`` stubs are excluded —
    they carry no runtime and therefore no coverage."""
    return path.endswith(".py")


def analyze_file(abs_path: str, reported_path: str) -> FileReport:
    """Read and analyze a single Python source file. ``reported_path`` is
    recorded on the result (typically relative to the analysis root)."""
    try:
        with open(abs_path, "r", encoding="utf-8") as fh:
            src = fh.read()
    except OSError as exc:
        raise unreadable_file(abs_path, exc)
    except UnicodeDecodeError as exc:
        raise unreadable_file(abs_path, exc)
    if _GENERATED_HEADER.search(src[:2048]):
        return FileReport(path=reported_path)
    return analyze_source(src, reported_path)
