"""Report formatters: human-readable text and stable, versioned JSON.

The JSON encoder sorts keys alphabetically and renders whole-number floats
without a trailing ``.0`` (e.g. ``30`` not ``30.0``) so output is diff-stable in
CI and byte-aligned with the Go/Kotlin/Swift/TypeScript siblings.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

from .version import TOOL_NAME


def pretty_report(report: Dict[str, Any], top_n: int) -> str:
    """Render a report as a human-readable text block: metadata, an optional
    notes section, a summary table, then the top-N methods by wCRAP descending.
    Methods above threshold are marked ``!``."""
    parts: List[str] = [_header(report), "\n"]
    if report["notes"]:
        parts.append(_notes_section(report))
        parts.append("\n")
    parts.append(_summary_section(report))
    parts.append("\n")
    parts.append(_top_methods(report, top_n))
    return "".join(parts)


def json_report(report: Dict[str, Any]) -> str:
    """Encode the report as indented JSON with sorted keys."""
    return json.dumps(_normalize(report), indent=2, sort_keys=True, ensure_ascii=False)


def error_text_line(envelope: Dict[str, str]) -> str:
    """Render an error envelope as a single-line CLI message."""
    return f"{TOOL_NAME}: [{envelope['code']}] {envelope['message']}"


def error_json(envelope: Dict[str, str]) -> str:
    """Render an error envelope as JSON: ``{"error": {...}}``."""
    return json.dumps({"error": envelope}, indent=2, sort_keys=True, ensure_ascii=False)


# -- internals -------------------------------------------------------------


def _normalize(obj: Any) -> Any:
    """Recursively turn integral floats into ints so JSON renders ``30`` not
    ``30.0`` — matching the siblings' number formatting. ``bool`` is left alone
    (it is a subclass of ``int`` but must stay ``true``/``false``)."""
    if isinstance(obj, dict):
        return {k: _normalize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_normalize(v) for v in obj]
    if isinstance(obj, bool):
        return obj
    if isinstance(obj, float) and obj.is_integer():
        return int(obj)
    return obj


def _header(report: Dict[str, Any]) -> str:
    if report["coverageDataPath"] is not None:
        coverage_line = report["coverageDataPath"]
    elif report["coverageAvailable"]:
        coverage_line = "(generated by the coverage run — cleaned up after run)"
    else:
        coverage_line = "(none — coverage assumed 0%)"
    return (
        f"{TOOL_NAME} {report['toolVersion']} — schema {report['schemaVersion']}\n"
        f"source:    {report['sourceRoot']}\n"
        f"coverage:  {coverage_line}\n"
        f"threshold: {report['threshold']:.1f}\n"
    )


def _notes_section(report: Dict[str, Any]) -> str:
    lines = ["Notes\n"]
    for note in report["notes"]:
        lines.append(f"  • {note}\n")
    return "".join(lines)


def _summary_section(report: Dict[str, Any]) -> str:
    s = report["summary"]
    lines = [
        "Summary\n",
        f"  files:     {s['fileCount']}\n",
        f"  types:     {s['typeCount']}  (crappy: {s['crappyTypeCount']})\n",
        f"  methods:   {s['methodCount']}  (crappy: {s['crappyMethodCount']})\n",
        f"  avg crap:  {s['averageCrap']:.2f}\n",
        f"  max crap:  {s['maxCrap']:.2f}\n",
        f"  avg cyc:   {s['averageComplexity']:.2f}\n",
        f"  avg cog:   {s['averageCognitiveComplexity']:.2f}\n",
        f"  avg wt:    {s['averageWeightedComplexity']:.2f}\n",
    ]
    if s["weightedCoverage"] is not None:
        lines.append(f"  coverage:  {s['weightedCoverage']:.1f}%\n")
    else:
        lines.append("  coverage:  unavailable (run without --no-coverage to gather it)\n")
    return "".join(lines)


def _top_methods(report: Dict[str, Any], top_n: int) -> str:
    ranked = sorted(report["methods"], key=lambda m: m["crap"], reverse=True)[:top_n]
    if not ranked:
        return "No methods analyzed.\n"
    crappy_total = report["summary"]["crappyMethodCount"]
    threshold_text = f"{report['threshold']:.1f}"
    lines: List[str] = []
    if crappy_total > 0:
        lines.append(
            f"Top methods by wCRAP ({crappy_total} above threshold {threshold_text}, marked !)\n"
        )
    else:
        lines.append(
            f"Top methods by wCRAP (none above threshold {threshold_text} — "
            f"ranked hotspots to watch)\n"
        )
    for m in ranked:
        marker = "!" if m["isCrappy"] else " "
        lines.append(
            "{marker} {crap}  cyc={cyc} cog={cog} wt={wt} cov={cov}%  {file}:{line}  {qn}\n".format(
                marker=marker,
                crap=_pad_start(f"{m['crap']:.2f}", 7),
                cyc=_pad_end(str(m["complexity"]), 3),
                cog=_pad_end(str(m["cognitiveComplexity"]), 3),
                wt=_pad_start(f"{m['weightedComplexity']:.2f}", 5),
                cov=_pad_start(f"{m['coverage']:.1f}", 5),
                file=m["file"],
                line=m["line"],
                qn=m["qualifiedName"],
            )
        )
    return "".join(lines)


def _pad_start(s: str, width: int) -> str:
    return s if len(s) >= width else " " * (width - len(s)) + s


def _pad_end(s: str, width: int) -> str:
    return s if len(s) >= width else s + " " * (width - len(s))
